### ISSUE TITLE
How can I replace the timestamps by logs own timestamps?

### ISSUE THREAD

**Issue by wangchaoforever** [metrico/qryn#169]
I use fluentd to collecet my logs to cloki.The logs arrive time is trivial to me. My logs contain it's own timestamps, How to use it's own timestamps replace the "time" in the loki UI ?

**Comment by wangchaoforever** [comment]
Juse like [this issue](https://github.com/grafana/loki/issues/1544) in loki

**Comment by lmangani** [comment]
@wangchaoforever  we support out of order timestamps just fine, but the timestamp itself is a responsibility of the client, not the receiver - so the issue is in your logging agent I suppose?

**Comment by akvlad** [comment]
That's not about qryn / loki. It's about the FluentD configuration. 

- You can configure one of these plugins https://docs.fluentd.org/parser according to the log lines format. 
- You can write your own parser plugin if your format is not supported by any of FluentD core parsers https://docs.fluentd.org/plugin-development/api-plugin-parser
- You can run your application through a wrapper reformatting your logs to be acceptable by one of FluenfD core parsers and run something like `nginx -g 'daemon off;' | mySpecialNginxParserToFluentD.py`

There are a lot of options to provide log lines parsing with timestamp and tag-values excavation.

**Comment by wangchaoforever** [comment]
I tried use fluentd to collect logs to qryn, I can not find the way to replace arrive time by log's own time.

**Comment by wangchaoforever** [comment]
Maybe I should use promtail.

**Comment by wangchaoforever** [comment]
@lmangani Is your client is Promtail?

**Comment by lmangani** [comment]
Not always. Depends on the job/system but they should all work fine - we use vector, grafana-agent, promtail and others such as our nodejs agent with equally successful results. Feel free to share an example of your configs if you need suggestions.

**Comment by wangchaoforever** [comment]
Now my problem is the timestamp. I can't use the log's own time to replace the arrive time. My settings of promtail is:
```
    pipeline_stages:
      - match:
          stages:
            - timestamp:
                source: time
                format: RFC1123
                fallback_formats: ['%Y-%m-%d %H:%M:%S.%N']
```
Can you gave me some recommend?

**Comment by akvlad** [comment]
@wangchaoforever you should configure a log parser according to the format you send. Promtail has a set of plugins named `pipeline_stages` https://grafana.com/docs/loki/latest/clients/promtail/configuration/#pipeline_stages . 
Well, it's pretty similar to fluentD parser & filter plugins, just another format of configuration.

**Comment by wangchaoforever** [comment]
@akvlad yes, I analyzed my logs already. The time of `source: time` in timestamp is my log's own time, but the timestamp in loki UI is the arrive time.

**Comment by wangchaoforever** [comment]
I have no idea now. Maybe I should use loki to verify if it's the qryn's problem?

**Comment by lmangani** [comment]
@wangchaoforever indeed cloki would not use the arrival time unless the time is wrongly formatted - and perhaps that's the issue. As @akvlad mentioned please share a couple example and we'll give it a try - Thanks!

**Comment by wangchaoforever** [comment]
That's my settings of Promtail's scrape_configs
```
scrape_configs:
  - job_name: test
    static_configs:
      - targets:
          - localhost
        labels:
          job: test
          host: localhost
          __path__: /data/test/*.log
    loki_push_api:
      use_incoming_timestamp: true
    pipeline_stages:
      - match:
          selector: '{job="test"}'
          stages:
            - multiline:
                firstline: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}'
                max_wait_time: 3s 
            - regex:
                expression: '^(?P<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3})(\s*)(?P<level>[\w]+)(\s*)-(\s+)(?P<log>.*)$'
            - labels:
                level: level
            - timestamp:
                source: time
                format: RFC1123
                fallback_formats: ['%Y-%m-%d %H:%M:%S.%N']
```
