### ISSUE TITLE
Unexpected request content-type

### ISSUE THREAD

**Issue by Cluas** [metrico/qryn#225]
{"level":50,"time":1665662651531,"pid":19,"hostname":"qryn-59f4b87599-z9jp9","name":"qryn","reqId":"req-1bn","err":"Unexpected request content-type\nError: Unexpected request content-type\n    at genericJSONOrYAMLParser (/app/qryn.js:210:11)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Parser.fn (/app/qryn.js:373:12)","msg":"Unexpected request content-type"}
{"level":30,"time":1665662651531,"pid":19,"hostname":"qryn-59f4b87599-z9jp9","name":"qryn","reqId":"req-1bn","res":{"statusCode":200},"responseTime":6.672591000795364,"msg":"request completed"}

**Comment by akvlad** [comment]
Hello @Cluas, which client do you use?
Can you check if the content-type of your request is exactly `application/json`?

**Comment by Cluas** [comment]
grafana agent config:
 ```yaml
  agent.yaml: |-
    server:
      log_level: debug

    traces:
      configs:
      - name: server_traces
        receivers:
          otlp:
            protocols:
              http:
                endpoint: "0.0.0.0:4318"
              grpc:
                endpoint: "0.0.0.0:4317"
        remote_write:
          - endpoint: qryn:3100
            insecure: true
```

**Comment by Cluas** [comment]
grafana agent logs:
``` bash
ts=2022-10-13T12:13:01Z level=error caller=exporterhelper/queued_retry.go:183 msg="Exporting failed. The error is not retryable. Dropping data." component=traces traces_config=server_traces kind=exporter data_type=traces name=otlp/0 error="Permanent error: rpc error: code = Unknown desc = transport: received unexpected content-type \"application/json; charset=utf-8\"" dropped_items=121
ts=2022-10-13T12:13:03.131212936Z caller=config_watcher.go:139 level=debug agent=prometheus component=cluster msg="waiting for next reshard interval" last_reshard=2022-10-13T12:13:03.131182084Z next_reshard=2022-10-13T12:14:03.131182084Z remaining=59.999995185s
ts=2022-10-13T12:13:12Z level=error caller=exporterhelper/queued_retry.go:183 msg="Exporting failed. The error is not retryable. Dropping data." component=traces traces_config=server_traces kind=exporter data_type=traces name=otlp/0 error="Permanent error: rpc error: code = Unknown desc = transport: received unexpected content-type \"application/json; charset=utf-8\"" dropped_items=155
ts=2022-10-13T12:13:23Z level=error caller=exporterhelper/queued_retry.go:183 msg="Exporting failed. The error is not retryable. Dropping data." component=traces traces_config=server_traces kind=exporter data_type=traces name=otlp/0 error="Permanent error: rpc error: code = Unknown desc = transport: received unexpected content-type \"application/json; charset=utf-8\"" dropped_items=136
ts=2022-10-13T12:13:33Z level=error caller=exporterhelper/queued_retry.go:183 msg="Exporting failed. The error is not retryable. Dropping data." component=traces traces_config=server_traces kind=exporter data_type=traces name=otlp/0 error="Permanent error: rpc error: code = Unknown desc = transport: received unexpected content-type \"application/json; charset=utf-8\"" dropped_items=133
ts=2022-10-13T12:13:43Z level=error caller=exporterhelper/queued_retry.go:183 msg="Exporting failed. The error is not retryable. Dropping data." component=traces traces_config=server_traces kind=exporter data_type=traces name=otlp/0 error="Permanent error: rpc error: code = Unknown desc = transport: received unexpected content-type \"application/json; charset=utf-8\"" dropped_items=107
ts=2022-10-13T12:13:56Z level=error caller=exporterhelper/queued_retry.go:183 msg="Exporting failed. The error is not retryable. Dropping data." component=traces traces_config=server_traces kind=exporter data_type=traces name=otlp/0 error="Permanent error: rpc error: code = Unknown desc = transport: received unexpected content-type \"text/plain; charset=utf-8\"" dropped_items=107
```

**Comment by Cluas** [comment]
grafana agent version: v0.27.0

**Comment by akvlad** [comment]
Ok. I'll recheck grafana agent. Thanks for the feedback.

**Comment by Cluas** [comment]
> Hello @Cluas, which client do you use? Can you check if the content-type of your request is exactly `application/json`?

`application/json; charset=utf-8`, `text/plain; charset=utf-8`

**Comment by akvlad** [comment]
After some investigation I've figured out that grafana agent supports otlp output but qryn doesn't have otlp input now, only zipkin.
I'll add a feature request for it.

**Comment by Cluas** [comment]
> After some investigation I've figured out that grafana agent supports otlp output but qryn doesn't have otlp input now, only zipkin. I'll add a feature request for it.

So what is the version of grafana agent in the documentation, and do I downgrade to the specified version first so I can use it first?

**Comment by Cluas** [comment]
Hi @akvlad , I used otel-collector zipkin exporter directly to qryn, now I have data, but I found that the event information is missing (only time, no other information)
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/10056928/195815044-028f215c-933c-4c1c-accd-26d010a8af70.png">

**Comment by lmangani** [comment]
@Cluas the ZipkinV2 ingestor should do fine, and works with otel libraries and zipkin sinks in our testing - could you share your config to replicate this scenario?

**Comment by Cluas** [comment]
> @Cluas the ZipkinV2 ingestor should do fine, and works with otel libraries and zipkin sinks in our testing - could you share your config to replicate this scenario? Are you browsing traces using the Tempo datasource?

1. config.yaml 

```yaml
 config.yaml: |
    receivers:
      jaeger:
        protocols:
          grpc:
            endpoint: 0.0.0.0:14250
          thrift_http:
            endpoint: 0.0.0.0:14268
          thrift_compact:
            endpoint: 0.0.0.0:6831
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 70
        spike_limit_percentage: 30
      batch:
        send_batch_size: 100
        send_batch_max_size: 1000
        timeout: 10s
      resourcedetection:
        detectors: [env]
        timeout: 5s
        override: false
      k8sattributes:
        auth_type: 'serviceAccount'
      resource:
        attributes:
          - key: app
            action: insert
            from_attribute: k8s.deployment.name
          - key: pod_name
            action: insert
            from_attribute: k8s.pod.name
    exporters:
      zipkin:
        endpoint: http://qryn.middleware.svc:3100/api/v2/spans
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [jaeger, otlp]
          processors: [memory_limiter, batch, resourcedetection, k8sattributes, resource]
          exporters: [zipkin]

```

2. Yes
