### ISSUE TITLE
从docker运行无法使用

### ISSUE THREAD

**Issue by zly-app** [metrico/qryn#238]
```yaml
version: '3'
services:
  qryn:
    image: qxip/qryn:v2.1.41
    container_name: qryn
    ports:
      - "10500:3100"
    environment:
      - CLICKHOUSE_SERVER=172.17.0.1
      - CLICKHOUSE_PROTO=http
      - CLICKHOUSE_PORT=10510
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_AUTH=default:abcdefghijk

  qryn-ck:
    image: yandex/clickhouse-server:21.3.20.1
    restart: unless-stopped
    container_name: qryn-ck
    volumes: 
      # chown -R 101:101 db log config.xml users.xml
      - "./config.xml:/etc/clickhouse-server/config.xml"
      - "./users.xml:/etc/clickhouse-server/users.xml"
    ports: 
      - 10510:8123
```

# 案例1

当 clickhouse 的密码是sha256标签 <password_sha256_hex> 时收到以下错误

```txt
{"level":50,"time":1667627342791,"pid":19,"hostname":"cf73f254b2b0","name":"qryn","err":"getaddrinfo ENOTFOUND default\nError: getaddrinfo ENOTFOUND default\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)","msg":"Error starting qryn"
```

# 案例2

当 clickhouse 的密码是明文标签 <password> 时收到以下错误

```txt
{"level":50,"time":1667627635995,"pid":19,"hostname":"ce7bea1a3628","name":"qryn","err":"Error: Request failed with status code 500\nResponse: [500] Code: 169, e.displayText() = DB::Exception: The column inserted_at cannot be used as a version column for storage ReplacingMergeTree because it is of type DateTime64(9, 'UTC') (must be of an integer type or of type Date or DateTime) (version 21.3.20.1 (official build))\n\nError: Request failed with status code 500\n    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:269:11)\n    at IncomingMessage.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1358:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","msg":"Error starting qryn"}
```

# 额外的

是否能增加小白的搭建方式, 从 clickhouse 搭建样例开始. 并且 CLICKHOUSE_DB 配置的db是否需要手动创建? 我不知道, 所以我直接使用 default 库
