### ISSUE TITLE
Please help to check a write performance issue

### ISSUE THREAD

**Issue by zhushilu** [metrico/qryn#297]
I had met a performance issue about the insert rate of qryn. As my testing,the insert rate is ～5K rows per second, have a huge gap between your description of 500K per second, so I have a question about how to improve my write rate enormously, my testing result and screenshot as below:

my  qryn docker-compose.yml:
```
version: '3'
services:
  qryn:
      image: qxip/qryn:latest
      ports:
        - "13100:3100"
      environment:
        - NODE_OPTIONS="--max-old-space-size=8192"
        - FASTIFY_METRICS=true
        - CLICKHOUSE_SERVER=172.30.2.100
        - CLICKHOUSE_AUTH=default:123456
        - CLICKHOUSE_PROTO=http
        - CLICKHOUSE_PORT=8133
        - CLICKHOUSE_DB=default
```

clickhouse docker-compose.yml
```
version: '3'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:22.10.2.11
    hostname: clickhouse
    container_name: clickhouse
    expose:
      - "9000"
    user: root
    privileged: true
    ports:
      - "8133:8123"
      - "9011:9000"
    volumes:
      - ./data/cloki:/var/lib/clickhouse
      - ./log/:/var/log/clickhouse-server/
      - ./etc/:/etc/clickhouse-server/
```

client configfile:
```
server:
  http_listen_port: 0
  grpc_listen_port: 0

limits_config:
  readline_rate: 1000000
  readline_burst: 1800000
  readline_rate_drop: true
  #max_streams: 100
  readline_rate_enabled: false

positions:
  filename: /opt/positions-kafka.yaml 
  sync_period: 10s

clients:
- url: http://172.30.2.100:13100/loki/api/v1/push
  batchwait: 2s
  batchsize: 10485760
  external_labels:
    cluster: pre

scrape_configs:
- job_name: kafka
  kafka:
    brokers:
    - 172.30.2.110:9092
    - 172.30.2.111:9092
    - 172.30.2.112:9092
    - 172.30.2.113:9092
    - 172.30.2.114:9092
    topics:
    - pre
    group_id: "pre"
    version: "0.10.2.0"
    labels:
      topic: pre
    use_incoming_timestamp: true
  pipeline_stages:
  - json:
      expressions:
        app_name: type
  - labels:
      level:
      app_name:
  - output:
      source: output
```
kafka monitor:
![image](https://user-images.githubusercontent.com/25314008/220344008-a3d18ed0-afa0-4e83-bcc7-368347685694.png)

host:
cpu: 96c
memory: 380G

qryn log:
```
{"level":30,"time":1676982299156,"pid":18,"hostname":"449f87a8614f","name":"qryn","reqId":"req-7pe","res":{"statusCode":204},"responseTime":2088.3939638137817,"msg":"request completed"}
{"level":30,"time":1676982299170,"pid":18,"hostname":"449f87a8614f","name":"qryn","reqId":"req-7pf","res":{"statusCode":204},"responseTime":1073.6763315200806,"msg":"request completed"}
{"level":30,"time":1676982299262,"pid":18,"hostname":"449f87a8614f","name":"qryn","reqId":"req-7pg","req":{"method":"POST","url":"/loki/api/v1/push","hostname":"172.30.27.101:13100","remoteAddress":"172.22.0.1","remotePort":57866},"msg":"incoming request"}
{"level":30,"time":1676982300235,"pid":18,"hostname":"449f87a8614f","name":"qryn","reqId":"req-7ph","req":{"method":"POST","url":"/loki/api/v1/push","hostname":"172.30.27.101:13100","remoteAddress":"172.22.0.1","remotePort":40592},"msg":"incoming request"}
{"level":30,"time":1676982301243,"pid":18,"hostname":"449f87a8614f","name":"qryn","reqId":"req-7pg","res":{"statusCode":204},"responseTime":1980.4352798461914,"msg":"request completed"}
{"level":30,"time":1676982301273,"pid":18,"hostname":"449f87a8614f","name":"qryn","reqId":"req-7ph","res":{"statusCode":204},"responseTime":1038.4373445510864,"msg":"request completed"}
{"level":30,"time":1676982301347,"pid":18,"hostname":"449f87a8614f","name":"qryn","reqId":"req-7pi","req":{"method":"POST","url":"/loki/api/v1/push","hostname":"172.30.27.101:13100","remoteAddress":"172.22.0.1","remotePort":57866},"msg":"incoming request"}
{"level":30,"time":1676982302306,"pid":18,"hostname":"449f87a8614f","name":"qryn","reqId":"req-7pj","req":{"method":"POST","url":"/loki/api/v1/push","hostname":"172.30.27.101:13100","remoteAddress":"172.22.0.1","remotePort":40592},"msg":"incoming request"}
{"level":30,"time":1676982303259,"pid":18,"hostname":"449f87a8614f","name":"qryn","reqId":"req-7pi","res":{"statusCode":204},"responseTime":1911.457106590271,"msg":"request completed"}
{"level":30,"time":1676982303284,"pid":18,"hostname":"449f87a8614f","name":"qryn","reqId":"req-7pj","res":{"statusCode":204},"responseTime":978.0444784164429,"msg":"request completed"}
{"level":30,"time":1676982303369,"pid":18,"hostname":"449f87a8614f","name":"qryn","reqId":"req-7pk","req":{"method":"POST","url":"/loki/api/v1/push","hostname":"172.30.27.101:13100","remoteAddress":"172.22.0.1","remotePort":57866},"msg":"incoming request"}
{"level":30,"time":1676982304407,"pid":18,"hostname":"449f87a8614f","name":"qryn","reqId":"req-7pl","req":{"method":"POST","url":"/loki/api/v1/push","hostname":"172.30.27.101:13100","remoteAddress":"172.22.0.1","remotePort":40592},"msg":"incoming request"}
{"level":30,"time":1676982305407,"pid":18,"hostname":"449f87a8614f","name":"qryn","reqId":"req-7pk","res":{"statusCode":204},"responseTime":2037.9065618515015,"msg":"request completed"}
{"level":30,"time":1676982305475,"pid":18,"hostname":"449f87a8614f","name":"qryn","reqId":"req-7pl","res":{"statusCode":204},"responseTime":1068.0935487747192,"msg":"request completed"}
```

I feel that qryn's response time (responseTime)  is too long。

refer：
https://qryn.metrico.in/#/performance
