### ISSUE TITLE
Bad Request: Not supported

### ISSUE THREAD

**Issue by gauravpareekk** [metrico/qryn#444]
Hi!

Dashboard fails with following issue
my grafana agent yml
```
server:
  http_tls_config:
    cert_file: /etc/grafana/grafana.crt
    key_file: /etc/grafana/grafana.key

metrics:
  wal_directory: /tmp/wal
  global: {}
  configs:
    - name: default
      remote_write:
        - url: http://localhost:3100/api/prom/push
          basic_auth:
            username: qryn
            password: xxx
logs:
  positions_directory: /tmp/loki-pos
  configs:
    - name: default
      scrape_configs: []
      clients:
        - url: http://qryn:xxx@localhost:3100/loki/api/v1/push
traces:
  configs:
    - name: default
      remote_write:
        - endpoint: localhost:3100
          insecure: true
          basic_auth:
            username: qryn
            password: xxx
      receivers:
        otlp:
          protocols:
            grpc:
            http:
              cors:
                allowed_origins:
                  - http://*
                max_age: 7200

integrations:
  app_agent_receiver_configs:
    - autoscrape:
        enable: true
        metrics_instance: 'default'
      # api_key: 'secret' # optional, if set, client will be required to provide it via x-api-key header
      instance: 'frontend'
      logs_instance: 'default'
      traces_instance: 'default'
      server:
        host: 0.0.0.0
        port: 12345
        cors_allowed_origins:
          - http://*
          #        cors_allowed_origins:
          #          - 'https://my-app.example.com'
      logs_labels: # labels to add to loki log record
        app: frontend # static value
        kind: # value will be taken from log items. exception, log, measurement, etc
      logs_send_timeout: 5000
      sourcemaps:
        download: true
```
qryn is running
```
version: '3.8'

services:
  qryn:
    image: qxip/qryn:3.1.2
    ports:
      - "3100:3100"
    environment:
      - CLICKHOUSE_SERVER=clickhouse-server
      - CLICKHOUSE_AUTH=qryn:supersecretpassword
      - CLICKHOUSE_DB=qryn
  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    environment:
      - CLICKHOUSE_USER=qryn
      - CLICKHOUSE_PASSWORD=xxx
    ports:
      - 8123:8123
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', '127.0.0.1:8123/ping']
      interval: 1s
      timeout: 1s
      retries: 30
```

dashboard is failing with error:
`qryn-qryn-1        | {"level":50,"time":1706524505440,"pid":20,"hostname":"ab7c2cb2986a","name":"qryn","reqId":"req-2k","err":"Not supported\nBad Request: Not supported\n    at topBottom (/app/parser/registry/parameterized_aggregation_registry/index.js:14:11)\n    at Object.topk (/app/parser/registry/parameterized_aggregation_registry/index.js:50:12)\n    at module.exports.transpile (/app/parser/transpiler.js:228:49)\n    at instantQueryScan (/app/lib/db/clickhouse.js:255:29)\n    at Object.handler (/app/lib/handlers/query.js:30:28)\n    at routeOptions.handler (/app/node_modules/@fastify/websocket/index.js:150:24)\n    at preHandlerCallback (/app/node_modules/fastify/lib/handleRequest.js:137:37)\n    at validationCompleted (/app/node_modules/fastify/lib/handleRequest.js:121:5)\n    at preValidationCallback (/app/node_modules/fastify/lib/handleRequest.js:98:5)\n    at handler (/app/node_modules/fastify/lib/handleRequest.js:75:7)","msg":"Not supported"}`
