### ISSUE TITLE
Error with npm in qryn 3.2.9

### ISSUE THREAD

**Issue by mk-raven** [metrico/qryn#472]
After update qryn to 3.2.9 in kubernetes by helm chart we had a problem with qryn when stared pod.

Logs in container:

```
2345678910111213> qryn@3.1.1 start
node qryn.mjs

npm ERR! code EROFS
npm ERR! syscall open
npm ERR! path /home/qryn/.npm/_cacache/tmp/a6592e19
npm ERR! errno -30
npm ERR! rofs EROFS: read-only file system, open '/home/qryn/.npm/_cacache/tmp/a6592e19'
npm ERR! rofs Often virtualized file systems, or other file systems
npm ERR! rofs that don't support symlinks, give this error.

npm ERR! Log files were not written due to an error writing to the directory: /home/qryn/.npm/_logs
npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal

```

Helm values:
```
affinity: {}
autoscaling:
  enabled: false
  maxReplicas: 100
  minReplicas: 20
  targetCPUUtilizationPercentage: 400
  targetMemoryUtilizationPercentage: 600
env:
  BULK_MAXAGE: 4000
  BULK_MAXCACHE: 100000
  BULK_MAXSIZE: 10000000
  CLICKHOUSE_AUTH: user:pass
  CLICKHOUSE_DB: qryn
  CLICKHOUSE_PORT: 9090
  CLICKHOUSE_PROTO: http
  CLICKHOUSE_SERVER: chproxy.chproxy.svc
  CLICKHOUSE_TIMEFIELD: record_datetime
  CLUSTER_NAME: data
  DISTINGUISH_LOGS_METRICS: 1
  FASTIFY_BODYLIMIT: 524288000
  FASTIFY_MAXREQUESTS: 0
  FASTIFY_METRICS: true
  FASTIFY_REQUESTTIMEOUT: 30000
  HOST: 0.0.0.0
  LABELS_DAYS: 7
  LOG_LEVEL: error
  NODE_OPTIONS: --max-old-space-size=61440
  PORT: 3100
  SAMPLES_DAYS: 7
fullnameOverride: qryn-write
image:
  repository: qxip/qryn
  tag: 3.2.9
imageCredentials: {}
imagePullSecrets:
  nameOverride: ""
ingress:
  annotations: {}
  className: ""
  enabled: false
  hosts:
  - host: chart-example.local
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []
kubernetesClusterDomain: ""
livenessProbe:
  enabled: true
  endpoint: /metrics
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podLabels:
- qryn
podSecurityContext:
  fsGroup: 999
replicas: 1
resources:
  limits:
    cpu: 5
    memory: 4096Mi
  requests:
    cpu: 1
    memory: 512Mi
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 999
service:
  port: 3100
  type: ClusterIP
serviceMonitor:
  enabled: true
  interval: 30s
  path: /metrics
  port: 3100
  portName: http
  scheme: http
  type: ClusterIP
tolerations: []

```
