### ISSUE TITLE
Issue with Log  Viewing in Qryn Setup with Docker

### ISSUE THREAD

**Issue by raushanraja** [metrico/qryn#517]
Hello, I'm currently setting up Qryn on my local system using Docker.

I've followed the steps in the getting started guide and successfully launched the containers. Next, I attempted to send logs using the API through curl. However, I'm encountering an issue where I'm unable to view any logs in qryn-view. I would appreciate any assistance with resolving this issue and would like to know if there's a step I might have missed.

- docker-compose.yml
```yaml
volumes:
    grafana_data: {}
    clickhouse_data: {}

services:
  qryn:
    image: qxip/qryn:latest
    ports:
      - "3100:3100"
    environment:
      - CLICKHOUSE_SERVER=clickhouse-server
      - CLICKHOUSE_AUTH=qryn:supersecretpassword
      - CLICKHOUSE_DB=qryn
  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    environment:
      - CLICKHOUSE_USER=qryn
      - CLICKHOUSE_PASSWORD=supersecretpassword
    ports:
      - 8123:8123
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', '127.0.0.1:8123/ping']
      interval: 1s
      timeout: 1s
      retries: 30
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_DEFAULT_THEME=light
      - GF_EXPLORE_ENABLED=true
      - GF_ALERTING_ENABLED=false
      - GF_UNIFIED_ALERTING_ENABLED=true
      - GF_FEATURE_TOGGLES_ENABLE=traceToMetrics,publicDashboards,tempoApmTable
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - qryn
```

- Here is docker-compose ps output
![2024-06-15-215552_1809x174_scrot](https://github.com/metrico/qryn/assets/23188940/853401bb-4ae8-4cc8-bee9-82162088e39b)

- curl command I use to push log
```sh
curl -i -XPOST -H "Content-Type: application/json" http://localhost:3100/loki/api/v1/push \
     --data '{"streams":[{"stream":{"type":"test"},"values":[['$(date +"%s%N")', "hello qryn"]]}]}'
```
- Output after running the command
![2024-06-15-214852_915x350_scrot](https://github.com/metrico/qryn/assets/23188940/bd6aa6ef-0347-482e-b781-adf5352702a7)

- Few logs from container after running the curl command
![2024-06-15-215131_926x442_scrot](https://github.com/metrico/qryn/assets/23188940/18870853-ee0b-4491-a37e-c7d22c2fce69)
