### ISSUE TITLE
No new data written to ClickHouse

### ISSUE THREAD

**Issue by Krernertok** [metrico/qryn#608]
I have a qryn setup with:
  - 5 qryn instances (autoscaled)
  - 2 ClickHouse instances with a tiered storage setup (writing first to local disk then moving to a locally cached blob storage "disk")
  - 3 ClickHouse Keeper instances

The data fed to qryn is collected and sent by Grafana Alloy.

This setup has been working with the same qryn configuration (see below) until I added monitoring for another AKS cluster, i.e. I configured another set of Alloy instances to send data to qryn. The first bottleneck was the limits set for the qryn instances. After adding more resources, the local disk ClickHouse writes to initially became full. After adding more disk space to the ClickHouse instances, everything worked for a while. Then no new data appeared when querying the metrics and logs with Grafana or qryn's web UI. Grepping the ClickHouse logs shows that all `INSERT INTO` queries were run against `*_dist` tables instead of non-dist tables (like `samples_v3` or `metrics_15s`).

Here is the qryn configuration (deployed using Flux):

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qryn
  namespace: qryn
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/qryn-helm-0.1.3-ahr.v0.2.tgz
      reconcileStrategy: ChartVersion
      version: '0.1.3'
      sourceRef:
        kind: GitRepository
        name: flux-conf
        namespace: cluster-config
      interval: 5m
  values:
    kubernetesClusterDomain: cluster.local
    image:
      repository: qxip/qryn
      tag: 3.2.37
    imagePullSecrets:
      nameOverride: ""
    nameOverride: ""
    fullnameOverride: <removed>
    imageCredentials: {}
    replicas: 1
    service:
      type: ClusterIP
      port: 3100
    livenessProbe:
      enabled: false
      endpoint: "/metrics"
    # podAnnotations: {}
    # podLabels: {}
    podLabels:
      - qryn
    nodeSelector:
      kubernetes.io/os: linux
    # tolerations: []
    # affinity: {}
    resources:
      limits:
        cpu: 2.0
        memory: 1Gi
      requests:
        cpu: 1.0 
        memory: 500Mi
    # serviceMonitor:
    #   enabled: true
    #   portName: http
    #   port: 3100
    #   interval: "30s"
    #   scheme: "http"
    #   path: /metrics
      # type: ClusterIP
      # labels: {}
      # tlsConfig: {}
      # metricRelabelings: []
      # relabelings: []
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80
    # automountServiceAccountToken: false
    securityContext:
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
    ingress:
      enabled: true
      className: "int-nginx"
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        nginx.ingress.kubernetes.io/use-regex: "true"
      hosts:
        - host: <removed>
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
      #  - secretName: chart-example-tls
      #    hosts:
      #      - chart-example.local
    env:
      CLICKHOUSE_SERVER: "clickhouse-qryn-db.qryn.svc.cluster.local"
      CLICKHOUSE_PORT: "8123"
      CLICKHOUSE_DB: "qryn"
      CLICKHOUSE_AUTH: <removed>
      # CLICKHOUSE_PROTO: "http"
      # CLICKHOUSE_TIMEFIELD: "record_datetime"
      CLUSTER_NAME: "qryn-cluster"
      STORAGE_POLICY: "azure_policy"
      # BULK_MAXAGE: "2000"
      # BULK_MAXSIZE: "5000"
      # BULK_MAXCACHE: "50000"
      # LABELS_DAYS: "7"
      # SAMPLES_DAYS: "7"
      # HOST: "0.0.0.0"
      # PORT: "3100"
      # QRYN_LOGIN: ""
      # QRYN_PASSWORD: ""
      # READONLY: "false"
      # OMIT_CREATE_TABLES: "false"
      # FASTIFY_BODYLIMIT: "5242880"
      # FASTIFY_REQUESTTIMEOUT: "0"
      # FASTIFY_MAXREQUESTS: "0"
      FASTIFY_METRICS: "true"
      # ADVANCED_PROMETHEUS_MAX_SAMPLES: "5000000"
      # CORS_ALLOW_ORIGIN: 	"*"
      # TEMPO_SPAN: "24"
      # TEMPO_TAGTRACE: "false"
      DEBUG: "false"
      LOG_LEVEL: "warn"
      # HASH: "xxhash64"
      # ALERTMAN_URL: "false"
      # ADVANCED_SAMPLES_ORDERING: "timestamp_ns"
```

Here is an excerpt from the ClickHouse logs:

```
2025.01.14 07:49:49.467281 [ 1476 ] {} <Debug> HTTP-Session-f2a8a20a-6684-4bfc-a6b1-d65a51e1d664: Authenticating user 'default' from [::ffff:10.244.9.23]:46298
2025.01.14 07:49:49.467343 [ 1476 ] {} <Debug> HTTP-Session-f2a8a20a-6684-4bfc-a6b1-d65a51e1d664: f2a8a20a-6684-4bfc-a6b1-d65a51e1d664 Authenticated with global context as user 94309d50-4f52-5250-31bd-74fecac179db
2025.01.14 07:49:49.467361 [ 1476 ] {} <Debug> HTTP-Session-f2a8a20a-6684-4bfc-a6b1-d65a51e1d664: Creating session context with user_id: 94309d50-4f52-5250-31bd-74fecac179db
2025.01.14 07:49:49.467742 [ 1476 ] {1cfea6b1-d647-4d6b-8566-c1c906dae430} <Debug> executeQuery: (from [::ffff:10.244.9.23]:46298) INSERT INTO qryn.samples_v3_dist(fingerprint, timestamp_ns, value, string, type) FORMAT JSONEachRow  (stage: Complete)
2025.01.14 07:49:49.470218 [ 1476 ] {1cfea6b1-d647-4d6b-8566-c1c906dae430} <Debug> executeQuery: Read 2000 rows, 125.67 KiB in 0.002532 sec., 789889.4154818326 rows/sec., 48.47 MiB/sec.
2025.01.14 07:49:49.470588 [ 1476 ] {1cfea6b1-d647-4d6b-8566-c1c906dae430} <Debug> DynamicQueryHandler: Done processing query
2025.01.14 07:49:49.470620 [ 1476 ] {1cfea6b1-d647-4d6b-8566-c1c906dae430} <Debug> MemoryTracker: Query peak memory usage: 398.25 KiB.
2025.01.14 07:49:49.470649 [ 1476 ] {} <Debug> HTTP-Session-f2a8a20a-6684-4bfc-a6b1-d65a51e1d664: f2a8a20a-6684-4bfc-a6b1-d65a51e1d664 Logout, user_id: 94309d50-4f52-5250-31bd-74fecac179db
2025.01.14 07:49:49.556105 [ 1470 ] {} <Debug> HTTP-Session-f0838fa3-01ba-4071-8c63-9ea5facd74c7: Authenticating user 'default' from [::ffff:10.244.8.52]:56394
2025.01.14 07:49:49.556214 [ 1470 ] {} <Debug> HTTP-Session-f0838fa3-01ba-4071-8c63-9ea5facd74c7: f0838fa3-01ba-4071-8c63-9ea5facd74c7 Authenticated with global context as user 94309d50-4f52-5250-31bd-74fecac179db
2025.01.14 07:49:49.556245 [ 1470 ] {} <Debug> HTTP-Session-f0838fa3-01ba-4071-8c63-9ea5facd74c7: Creating session context with user_id: 94309d50-4f52-5250-31bd-74fecac179db
2025.01.14 07:49:49.556750 [ 1470 ] {04de0cf7-bfeb-47f5-aff6-41e25134584b} <Debug> executeQuery: (from [::ffff:10.244.8.52]:56394) INSERT INTO qryn.time_series_dist(date, fingerprint, labels, name, type) FORMAT JSONEachRow  (stage: Complete)
2025.01.14 07:49:49.559604 [ 1470 ] {04de0cf7-bfeb-47f5-aff6-41e25134584b} <Debug> executeQuery: Read 491 rows, 306.81 KiB in 0.002941 sec., 166950.01700102005 rows/sec., 101.88 MiB/sec.
2025.01.14 07:49:49.559946 [ 1470 ] {04de0cf7-bfeb-47f5-aff6-41e25134584b} <Debug> DynamicQueryHandler: Done processing query
2025.01.14 07:49:49.559974 [ 1470 ] {04de0cf7-bfeb-47f5-aff6-41e25134584b} <Debug> MemoryTracker: Query peak memory usage: 933.39 KiB.
2025.01.14 07:49:49.559997 [ 1470 ] {} <Debug> HTTP-Session-f0838fa3-01ba-4071-8c63-9ea5facd74c7: f0838fa3-01ba-4071-8c63-9ea5facd74c7 Logout, user_id: 94309d50-4f52-5250-31bd-74fecac179db
2025.01.14 07:49:49.561496 [ 1470 ] {} <Debug> HTTP-Session-e0f8993d-3b2b-4894-97bf-2c8ce82f4549: Authenticating user 'default' from [::ffff:10.244.8.52]:56394
2025.01.14 07:49:49.561540 [ 1470 ] {} <Debug> HTTP-Session-e0f8993d-3b2b-4894-97bf-2c8ce82f4549: e0f8993d-3b2b-4894-97bf-2c8ce82f4549 Authenticated with global context as user 94309d50-4f52-5250-31bd-74fecac179db
2025.01.14 07:49:49.561559 [ 1470 ] {} <Debug> HTTP-Session-e0f8993d-3b2b-4894-97bf-2c8ce82f4549: Creating session context with user_id: 94309d50-4f52-5250-31bd-74fecac179db
2025.01.14 07:49:49.561827 [ 1470 ] {b3656055-ea7c-4171-908c-4960e60e7820} <Debug> executeQuery: (from [::ffff:10.244.8.52]:56394) INSERT INTO qryn.samples_v3_dist(fingerprint, timestamp_ns, value, string, type) FORMAT JSONEachRow  (stage: Complete)
2025.01.14 07:49:49.563289 [ 1470 ] {b3656055-ea7c-4171-908c-4960e60e7820} <Debug> executeQuery: Read 297 rows, 21.15 KiB in 0.001518 sec., 195652.1739130435 rows/sec., 13.61 MiB/sec.
2025.01.14 07:49:49.563621 [ 1470 ] {b3656055-ea7c-4171-908c-4960e60e7820} <Debug> DynamicQueryHandler: Done processing query
2025.01.14 07:49:49.563669 [ 1470 ] {} <Debug> HTTP-Session-e0f8993d-3b2b-4894-97bf-2c8ce82f4549: e0f8993d-3b2b-4894-97bf-2c8ce82f4549 Logout, user_id: 94309d50-4f52-5250-31bd-74fecac179db
2025.01.14 07:49:49.573969 [ 1476 ] {} <Debug> HTTP-Session-d3727725-6e99-48b5-b20b-a7cc4d5b102d: Authenticating user 'default' from [::ffff:10.244.9.23]:46298
2025.01.14 07:49:49.574032 [ 1476 ] {} <Debug> HTTP-Session-d3727725-6e99-48b5-b20b-a7cc4d5b102d: d3727725-6e99-48b5-b20b-a7cc4d5b102d Authenticated with global context as user 94309d50-4f52-5250-31bd-74fecac179db
2025.01.14 07:49:49.574047 [ 1476 ] {} <Debug> HTTP-Session-d3727725-6e99-48b5-b20b-a7cc4d5b102d: Creating session context with user_id: 94309d50-4f52-5250-31bd-74fecac179db
2025.01.14 07:49:49.574340 [ 1476 ] {909536cd-c483-470d-b244-782a64c0e993} <Debug> executeQuery: (from [::ffff:10.244.9.23]:46298) INSERT INTO qryn.time_series_dist(date, fingerprint, labels, name, type) FORMAT JSONEachRow  (stage: Complete)
2025.01.14 07:49:49.575739 [ 1476 ] {909536cd-c483-470d-b244-782a64c0e993} <Debug> executeQuery: Read 7 rows, 1.80 KiB in 0.001458 sec., 4801.097393689986 rows/sec., 1.21 MiB/sec.
2025.01.14 07:49:49.576066 [ 1476 ] {909536cd-c483-470d-b244-782a64c0e993} <Debug> DynamicQueryHandler: Done processing query
2025.01.14 07:49:49.576119 [ 1476 ] {} <Debug> HTTP-Session-d3727725-6e99-48b5-b20b-a7cc4d5b102d: d3727725-6e99-48b5-b20b-a7cc4d5b102d Logout, user_id: 94309d50-4f52-5250-31bd-74fecac179db
2025.01.14 07:49:49.576909 [ 1476 ] {} <Debug> HTTP-Session-bbc74691-a9cf-4be7-9615-f532338b89a7: Authenticating user 'default' from [::ffff:10.244.9.23]:46298
2025.01.14 07:49:49.576976 [ 1476 ] {} <Debug> HTTP-Session-bbc74691-a9cf-4be7-9615-f532338b89a7: bbc74691-a9cf-4be7-9615-f532338b89a7 Authenticated with global context as user 94309d50-4f52-5250-31bd-74fecac179db
2025.01.14 07:49:49.577003 [ 1476 ] {} <Debug> HTTP-Session-bbc74691-a9cf-4be7-9615-f532338b89a7: Creating session context with user_id: 94309d50-4f52-5250-31bd-74fecac179db
2025.01.14 07:49:49.577241 [ 1476 ] {43bfab17-2c9c-4932-9b36-d73e509ad2fb} <Debug> executeQuery: (from [::ffff:10.244.9.23]:46298) INSERT INTO qryn.samples_v3_dist(fingerprint, timestamp_ns, value, string, type) FORMAT JSONEachRow  (stage: Complete)
2025.01.14 07:49:49.578471 [ 1476 ] {43bfab17-2c9c-4932-9b36-d73e509ad2fb} <Debug> executeQuery: Read 147 rows, 23.51 KiB in 0.001274 sec., 115384.61538461539 rows/sec., 18.02 MiB/sec.
2025.01.14 07:49:49.578782 [ 1476 ] {43bfab17-2c9c-4932-9b36-d73e509ad2fb} <Debug> DynamicQueryHandler: Done processing query
2025.01.14 07:49:49.578825 [ 1476 ] {} <Debug> HTTP-Session-bbc74691-a9cf-4be7-9615-f532338b89a7: bbc74691-a9cf-4be7-9615-f532338b89a7 Logout, user_id: 94309d50-4f52-5250-31bd-74fecac179db
2025.01.14 07:49:49.668538 [ 1248 ] {} <Debug> HTTP-Session-aada9fd0-06cd-4800-8359-f2cced80cd7d: Authenticating user 'default' from [::ffff:10.244.8.74]:56256
2025.01.14 07:49:49.668619 [ 1248 ] {} <Debug> HTTP-Session-aada9fd0-06cd-4800-8359-f2cced80cd7d: aada9fd0-06cd-4800-8359-f2cced80cd7d Authenticated with global context as user 94309d50-4f52-5250-31bd-74fecac179db
2025.01.14 07:49:49.668639 [ 1248 ] {} <Debug> HTTP-Session-aada9fd0-06cd-4800-8359-f2cced80cd7d: Creating session context with user_id: 94309d50-4f52-5250-31bd-74fecac179db
2025.01.14 07:49:49.669064 [ 1248 ] {0a2b196c-ae69-4595-8e1d-4b5720119e6b} <Debug> executeQuery: (from [::ffff:10.244.8.74]:56256) INSERT INTO qryn.time_series_dist(date, fingerprint, labels, name, type) FORMAT JSONEachRow  (stage: Complete)
2025.01.14 07:49:49.674313 [ 1248 ] {0a2b196c-ae69-4595-8e1d-4b5720119e6b} <Debug> executeQuery: Read 1845 rows, 808.35 KiB in 0.005329 sec., 346218.80277725647 rows/sec., 148.13 MiB/sec.
2025.01.14 07:49:49.674702 [ 1248 ] {0a2b196c-ae69-4595-8e1d-4b5720119e6b} <Debug> DynamicQueryHandler: Done processing query
2025.01.14 07:49:49.674730 [ 1248 ] {0a2b196c-ae69-4595-8e1d-4b5720119e6b} <Debug> MemoryTracker: Query peak memory usage: 2.16 MiB.
2025.01.14 07:49:49.674749 [ 1248 ] {} <Debug> HTTP-Session-aada9fd0-06cd-4800-8359-f2cced80cd7d: aada9fd0-06cd-4800-8359-f2cced80cd7d Logout, user_id: 94309d50-4f52-5250-31bd-74fecac179db
2025.01.14 07:49:49.678902 [ 1248 ] {} <Debug> HTTP-Session-3fe12594-03b2-4b00-85e6-3c7f574e25b0: Authenticating user 'default' from [::ffff:10.244.8.74]:56256
2025.01.14 07:49:49.678963 [ 1248 ] {} <Debug> HTTP-Session-3fe12594-03b2-4b00-85e6-3c7f574e25b0: 3fe12594-03b2-4b00-85e6-3c7f574e25b0 Authenticated with global context as user 94309d50-4f52-5250-31bd-74fecac179db
2025.01.14 07:49:49.678983 [ 1248 ] {} <Debug> HTTP-Session-3fe12594-03b2-4b00-85e6-3c7f574e25b0: Creating session context with user_id: 94309d50-4f52-5250-31bd-74fecac179db
2025.01.14 07:49:49.679375 [ 1248 ] {8f2cabfb-6395-40c8-80cd-8c2436a104cd} <Debug> executeQuery: (from [::ffff:10.244.8.74]:56256) INSERT INTO qryn.samples_v3_dist(fingerprint, timestamp_ns, value, string, type) FORMAT JSONEachRow  (stage: Complete)
2025.01.14 07:49:49.682074 [ 1248 ] {8f2cabfb-6395-40c8-80cd-8c2436a104cd} <Debug> executeQuery: Read 2000 rows, 149.65 KiB in 0.002764 sec., 723589.001447178 rows/sec., 52.87 MiB/sec.
2025.01.14 07:49:49.682379 [ 1248 ] {8f2cabfb-6395-40c8-80cd-8c2436a104cd} <Debug> DynamicQueryHandler: Done processing query
2025.01.14 07:49:49.682412 [ 1248 ] {8f2cabfb-6395-40c8-80cd-8c2436a104cd} <Debug> MemoryTracker: Query peak memory usage: 491.22 KiB.
2025.01.14 07:49:49.682431 [ 1248 ] {} <Debug> HTTP-Session-3fe12594-03b2-4b00-85e6-3c7f574e25b0: 3fe12594-03b2-4b00-85e6-3c7f574e25b0 Logout, user_id: 94309d50-4f52-5250-31bd-74fecac179db
```

I will set up a test instance of qryn against the same ClickHouse cluster to try to determine if I have misconfigured ClickHouse.
